#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
#agent.dump_env()
PEGAPROX_CONFIG_DIR = data.get("PEGAPROX_CONFIG_DIR", "/app/pegaprox/config") 
 
pegaprox = { 
 "PEGAPROX_CONFIG_DIR" : PEGAPROX_CONFIG_DIR ,
} 
agent.write_envfile("pegaprox.env", pegaprox) 
