#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.


def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]


# just before starting systemd unit
# agent.dump_env()

# Create podman volume for persistent config (SQLite DB, SSL certs, etc.)
agent.run_helper('podman', 'volume', 'create', 'pegaprox-config').check_returncode()

# Set default Traefik environment
agent.set_env("TRAEFIK_HTTP2HTTPS", str(True))
agent.set_env("TRAEFIK_LETS_ENCRYPT", str(False))
